# Generated by the windmill services transformer
from windmill.authoring import WindmillTestClient

def test_recordingSuite0():
    client = WindmillTestClient(__name__)

    client.click(link=u'Login')
    client.waits.forPageLoad(timeout=u'20000')
    client.type(text=u'admin', id=u'id_username')
    client.type(text=u'admin', id=u'id_password')
    client.click(xpath=u'/html/body/div/form/button')
    client.waits.forPageLoad(timeout=u'20000')
    client.waits.forElement(link=u'Edit', timeout=u'8000')
    client.click(link=u'Edit')
    client.waits.forPageLoad(timeout=u'20000')
    client.waits.forElement(timeout=u'8000', id=u'id_contact-email')
    client.click(id=u'id_contact-email')
    client.type(text=u'dudarev@gmail.comqqqqq', id=u'id_contact-email')
    client.click(xpath=u"//div[@id='submit-buttons']/button")
    client.click(xpath=u"//div[@id='response-modal-error']/div[3]/a")
    client.click(id=u'id_contact-email')
    client.type(text=u'dudarev@gmail.com', id=u'id_contact-email')
    client.click(xpath=u"//div[@id='submit-buttons']/button")
    client.click(link=u'OK')
    client.open(url=u'/accounts/logout/')
    client.waits.forPageLoad(timeout=u'20000')
    client.open(url=u'/')
